# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'U.O.ME' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for U.O.ME
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'SDWebImage'
end
